export const Fonts = {
    black: 'Poppins-Black',
    black_italic: 'Poppins-BlackItalic',
    bold: 'Poppins-Bold',
    bold_italic: 'Poppins-BoldItalic',
    extra_bold: 'Poppins-ExtraBold',
    extra_bold_italic: 'Poppins-ExtraBoldItalic',
    extra_light: 'Poppins-ExtraLight',
    extra_light_italic: 'Poppins-ExtraLightItalic',
    italic: 'Poppins-Italic',
    light: 'Poppins-Light',
    light_italic: 'Poppins-LightItalic',
    medium: 'Poppins-Medium',
    medium_italic: 'Poppins-MediumItalic',
    regular: 'Poppins-Regular',
    semi_bold: 'Poppins-SemiBold',
    semi_bold_italic: 'Poppins-SemiBoldItalic',
    thin: 'Poppins-Thin',
    thin_italic: 'Poppins-ThinItalic'
};
