export const MAIN_FONT = {
    font_black: "Montserrat-Black",
    font_black_italic: "Montserrat-BlackItalic",
    font_bold: "Montserrat-Bold",
    font_bold_italic: "Montserrat-BoldItalic",
    font_extra_bold: "Montserrat-ExtraBold",
    font_extra_bold_italic: "Montserrat-ExtraBoldItalic",
    font_extra_light: "Montserrat-ExtraLight",
    font_extra_light_italic: "Montserrat-ExtraLightItalic",
    font_italic: "Montserrat-Italic",
    font_light: "Montserrat-Light",
    font_light_italic: "Montserrat-LightItalic",
    font_medium: "Montserrat-Medium",
    font_medium_italic: "Montserrat-MediumItalic",
    font_regular: "Montserrat-Regular",
    font_semi_bold: "Montserrat-SemiBold",
    font_semi_bold_italic: "Montserrat-SemiBoldItalic",
    font_thin: "Montserrat-Thin",
    font_thin_italic: "Montserrat-ThinItalic",
};
